apiVersion: v1
kind: Secret
metadata:
  name: bookinfo-dev-ratings-mongodb-secret
  namespace: bookinfo-dev
type: Opaque
data:
  mongodb-root-password:
  mongodb-password:
  mongodb-root-passwords:
  mongodb-passwords:
