apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: http://bookinfo.0xnutx.space/ratings
maintainers:
  - name: Developer
    email: 0xnutx@nutx.com
